services:
  dbCommandQuery:
    container_name: "data_base_Command"
    image: mariadb:latest
    restart: always
    environment:
      SERVER: localhost
      USER: root
      MARIADB_ROOT_PASSWORD: 12345
    ports:
      - 3306:3306