services:
  dbCommand:
    container_name: "data_base_Command"
    image: mariadb:latest
    restart: always
    environment:
      SERVER: localhost
      USER: root
      MARIADB_ROOT_PASSWORD: 12345
      DATABASE: ClientAndFounderCommand    
    ports:
      - 3306:3306
  dbQuery:
    container_name: "data_base_Query"
    image: mariadb:latest
    restart: always
    environment:
      SERVER: localhost
      USER: root
      MARIADB_ROOT_PASSWORD: 12345
      DATABASE: ClientAndFounderQuery    
    ports:
      - 3307:3307