// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Teledock.dbContext;

#nullable disable

namespace Teledock.Migrations
{
    [DbContext(typeof(DbCommand))]
    [Migration("20241202140725_InitCommand")]
    partial class InitCommand
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Teledock.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Inn")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Инн");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("имя");

                    b.Property<int>("_TypeClient")
                        .HasColumnType("int")
                        .HasColumnName("тип");

                    b.Property<DateTime>("dateAdd")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("дата добавления");

                    b.Property<DateTime?>("dateUpdate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("дата обновления");

                    b.HasKey("Id");

                    b.HasIndex("Inn")
                        .IsUnique();

                    b.ToTable("клиенты");
                });

            modelBuilder.Entity("Teledock.Models.Founder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("FIO")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("фио");

                    b.Property<string>("Inn")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Инн");

                    b.Property<DateTime>("dateAdd")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("дата добавления");

                    b.Property<DateTime?>("dateUpdate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("дата обновления");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("Inn")
                        .IsUnique();

                    b.ToTable("учредители");
                });

            modelBuilder.Entity("Teledock.Models.Founder", b =>
                {
                    b.HasOne("Teledock.Models.Client", "client")
                        .WithMany("founders")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("client");
                });

            modelBuilder.Entity("Teledock.Models.Client", b =>
                {
                    b.Navigation("founders");
                });
#pragma warning restore 612, 618
        }
    }
}
