name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main
            

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Проверка исходного кода
        uses: actions/checkout@v2

      - name: Установка зависимостей для Docker
        run: |
          sudo apt-get remove -y containerd containerd.io
          sudo apt-get update
          sudo apt-get install -y \
            apt-transport-https \
            ca-certificates \
            curl \
            software-properties-common

      - name: Добавление Docker репозитория
        run: |
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update

      - name: Установка Docker
        run: |
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io
          sudo systemctl start docker
          sudo systemctl enable docker

      - name: Установка Docker Compose
        run: |
          sudo apt-get install -y curl
          DOCKER_COMPOSE_VERSION=1.29.2
          sudo curl -L "https://github.com/docker/compose/releases/download/$DOCKER_COMPOSE_VERSION/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Проверка установки
        run: |
          docker --version
          docker-compose --version

      - name: Checkout repository
        uses: actions/checkout@v3  # Клонируем репозиторий

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'  # Указываем версию .NET, с которой будет собираться проект (возможно, тебе нужно будет изменить на 7.0 или другую версию, в зависимости от того, что используется в твоем проекте)

      - name: Restore dependencies
        run: dotnet restore  # Восстанавливаем зависимости проекта
      - name: скачиваем dotnet ef
        run : dotnet tool install --global dotnet-ef # он нам нужен для миграций
      - name: сбилдить библиотки классов
        run: |
            cd Teledock.Domain
            dotnet build
            cd ../Teledock.Infrastructure
            dotnet build
            cd ../Teledock.Application
            dotnet build
            cd ..
            
      - name: поднять докер
        run: docker-compose up -d #поднимаем контейнер с базами данных
      - name: Build project
        run: dotnet build --configuration Release  # Сборка проекта в режиме Release

      - name: Run tests (optional)
        run: dotnet test  # Запуск тестов, если они есть в проекте
      # Здесь добавьте шаги для сборки, тестирования и развертывания вашего приложения